const buttons = document.querySelectorAll("button")
let newButton = document.createElement("button")
document.body.appendChild(newButton)
console.log(buttons)
// let item = localStorage.getItem("salam")
// localStorage.setItem("salam")